### ISSUE TITLE
pre-commit exclude is ignored

### ISSUE THREAD

**Issue by shanee-spring** [pre-commit/mirrors-mypy#1]
Question

Is it possible to ignore directories and files when using the mypy pre-commit by specifying `exclude`?

My `.pre-commit-config.yaml` file:
```
default_language_version:
    python: python3.6
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: flake8
        args: [ignore_me, not_me]
        exclude: 'ignore_me' # This works, and skips the directory ignore_me, and only runs flake8 on the not_me directory
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.670
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, .]
        exclude: 'ignore_me' # I still see mypy errors from the ignore_me directory
```

When I commit in my repository, I still see mypy errors from `ignore_me` and I don't get the flake8 errors.

**Comment by asottile** [comment]
`exclude` acts on the files that get passed through to the underlying tools.

In your first example, `ignore_me` will still get passed through to `flake8` because it is in the `args`, `exclude` only acts on the files that would have been passed to flake8

`mypy` is a different beast however, it follows imports in the files passed to it and will produce error messages if there are errors in the imports it follows.  You can disable following imports (but then it's not very useful as a type checker) or configure mypy to ignore type errors in those specific files.  Here's an example:

https://github.com/pre-commit/pre-commit-hooks/blob/d85c06d9a6f4057c4daba14de781637810a1a3f0/mypy.ini#L7-L12


If you want to clarify the behaviour of `ignore` you can use the `identity` meta hook to play with it:

```
$ git ls-files
.pre-commit-config.yaml
ignore_me/a
not_me/b


$ pre-commit  run --all-files
identity (args)..........................................................Passed
hookid: identity

ignore_me
(files start after)
.pre-commit-config.yaml
not_me/b

identity (no args).......................................................Passed
hookid: identity

.pre-commit-config.yaml
not_me/b
```

**Comment by konstantinmiller** [comment]
Sorry but it's still unclear to me how to make mypy ignore errors in specific files. The link in your post doesn't provide an example of that.

**Comment by asottile** [comment]
you'll note I didn't use `exclude` anywhere, I instead configured mypy settings for individual modules

**Comment by RayBB** [comment]
@asottile following up on your question [here](https://github.com/pre-commit/mirrors-mypy/issues/55#issuecomment-899088080) for a reproducible example of this issue.

I have a reproducible example of the issue here https://github.com/RayBB/pre-commit-mirrors-mypy-error

To make it super clear I added to github actions that run mypy, one through precommit and one without.
* The [build **without** pre-commit](https://github.com/RayBB/pre-commit-mirrors-mypy-error/runs/4797161486?check_suite_focus=true) only detected one error and successfully excluded the other.
* The [build **with** pre-commit](https://github.com/RayBB/pre-commit-mirrors-mypy-error/runs/4797161487?check_suite_focus=true) had two errors because it didn't exclude the folder as configured.

Big thanks to you for maintaining this project and answering so many question :)

**Comment by asottile** [comment]
as explained above and many times in the issue tracker and [pre-commit docs](https://pre-commit.com/#arguments-pattern-in-hooks), pre-commit runs tools by passing files to them.  so `mypy .` is not the equivalent call but rather `mypy $(git ls-files -- '*.py')` (or similar)

**Comment by mattgauntseo-sentry** [comment]
I just ran into this issue and was struggling to follow this thread with the right solution (although it explained the behavior I was seeing).

In the end I updated the `.pre-commit-config.yaml` from:

```yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
```

To:

```yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        exclude: ^dir-to-exclude/
```

This resulted in the desired behavior for me.

**NOTE:** This is an exclude in the pre-commit tool and **not** an exclude in mypy.
