### ISSUE TITLE
--strict mode is not respected

### ISSUE THREAD

**Issue by omry** [pre-commit/mirrors-mypy#10]
Config:
```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
      - id: mypy
        args: [--strict]
```

Run hook manually:
```
omry@omry-fedora:~/dev/hydra (precommit)$ pre-commit run --files hydra/main.py  
mypy.....................................................................Passed
```
Run mypy manually:
```
(hydra37) omry@omry-fedora:~/dev/hydra (precommit)$ mypy --strict hydra/main.py
hydra/main.py:11: error: Function is missing a type annotation for one or more arguments
Found 1 error in 1 file (checked 1 source file)
```

**Comment by asottile** [comment]
that config is invalid, can you show your actual config?

**Comment by omry** [comment]
```yaml
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 'c54b3dd'
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [-e, git+git://github.com/pycqa/pyflakes.git@1911c20#egg=pyflakes]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
      - id: mypy
        args: [--strict]
```

**Comment by omry** [comment]
Is there a way to see the exact command used to run the hook? I tried --verbose but it only showed the output.

**Comment by asottile** [comment]
`rev: ''` should be producing an error -- that's not a valid revision, can you show me a terminal session (with PS1) of:

```bash
cat .pre-commit-config.yaml
pre-commit --version
pre-commit run mypy --verbose --files hydra/main.py
```

**Comment by omry** [comment]
```
(hydra37) omry@omry-fedora:~/dev/hydra (precommit)$ cat .pre-commit-config.yaml
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 'c54b3dd'
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [-e, git+git://github.com/pycqa/pyflakes.git@1911c20#egg=pyflakes]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
      - id: mypy(hydra37) omry@omry-fedora:~/dev/hydra (precommit)$ pre-commit --version
pre-commit 1.20.0
(hydra37) omry@omry-fedora:~/dev/hydra (precommit)$ pre-commit run mypy --verbose --files hydra/main.py
[mypy] mypy..............................................................Passed
hookid: mypy

Success: no issues found in 1 source file

```

**Comment by omry** [comment]
(hydra37) omry@omry-fedora:~/dev/hydra (precommit)$ pip freeze | grep pre-commit
pre-commit==1.20.0

**Comment by omry** [comment]
```
(hydra37) omry@omry-fedora:~/dev/hydra (precommit)$ pip install --upgrade pre-commit
Collecting pre-commit
  Using cached https://files.pythonhosted.org/packages/df/30/22425aa6680370ba06de107e82eb3fc6159f462619b941241e96dd6bd79b/pre_commit-1.21.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: identify>=1.0.0 in /home/omry/miniconda3/envs/hydra37/lib/python3.7/site-packages (from pre-commit) (1.4.7)
Requirement already satisfied, skipping upgrade: six in /home/omry/miniconda3/envs/hydra37/lib/python3.7/site-packages (from pre-commit) (1.12.0)
Requirement already satisfied, skipping upgrade: pyyaml in /home/omry/miniconda3/envs/hydra37/lib/python3.7/site-packages (from pre-commit) (5.3b1)
Requirement already satisfied, skipping upgrade: aspy.yaml in /home/omry/miniconda3/envs/hydra37/lib/python3.7/site-packages (from pre-commit) (1.3.0)
Requirement already satisfied, skipping upgrade: nodeenv>=0.11.1 in /home/omry/miniconda3/envs/hydra37/lib/python3.7/site-packages (from pre-commit) (1.3.3)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in /home/omry/miniconda3/envs/hydra37/lib/python3.7/site-packages (from pre-commit) (0.23)
Requirement already satisfied, skipping upgrade: toml in /home/omry/miniconda3/envs/hydra37/lib/python3.7/site-packages (from pre-commit) (0.10.0)
Requirement already satisfied, skipping upgrade: cfgv>=2.0.0 in /home/omry/miniconda3/envs/hydra37/lib/python3.7/site-packages (from pre-commit) (2.0.1)
Requirement already satisfied, skipping upgrade: virtualenv>=15.2 in /home/omry/miniconda3/envs/hydra37/lib/python3.7/site-packages (from pre-commit) (16.7.7)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /home/omry/miniconda3/envs/hydra37/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->pre-commit) (0.6.0)
Requirement already satisfied, skipping upgrade: more-itertools in /home/omry/miniconda3/envs/hydra37/lib/python3.7/site-packages (from zipp>=0.5->importlib-metadata; python_version < "3.8"->pre-commit) (7.2.0)
Installing collected packages: pre-commit
  Found existing installation: pre-commit 1.20.0
    Uninstalling pre-commit-1.20.0:
      Successfully uninstalled pre-commit-1.20.0
Successfully installed pre-commit-1.21.0
(hydra37) omry@omry-fedora:~/dev/hydra (precommit)$ pre-commit run mypy --verbose --files hydra/main.py
mypy.....................................................................Passed
- hook id: mypy
- duration: 0.11s

Success: no issues found in 1 source file

(hydra37) omry@omry-fedora:~/dev/hydra (precommit)$ 

```

**Comment by asottile** [comment]
I see no `args`

the rev thing is weird though, what version of git do you have? I suspect a bug in git for that

**Comment by omry** [comment]
Yeah, I must have dropped the --args somehow.
I now get errors, but more than I bargained for.
```
$ pre-commit run mypy --verbose --files hydra/main.py 
mypy.....................................................................Failed
- hook id: mypy
- duration: 1.04s
- exit code: 1

hydra/types.py:4: error: Cannot find implementation or library stub for module named 'omegaconf'
hydra/types.py:4: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
hydra/plugins/common/utils.py:12: error: Cannot find implementation or library stub for module named 'omegaconf'
hydra/plugins/common/utils.py:24: error: unused 'type: ignore' comment
hydra/plugins/common/utils.py:45: error: unused 'type: ignore' comment
hydra/_internal/config_loader.py:10: error: Cannot find implementation or library stub for module named 'omegaconf'
hydra/utils.py:6: error: Cannot find implementation or library stub for module named 'omegaconf'
hydra/plugins/sweeper.py:8: error: Cannot find implementation or library stub for module named 'omegaconf'
hydra/plugins/launcher.py:8: error: Cannot find implementation or library stub for module named 'omegaconf'
hydra/plugins/step_sweeper.py:9: error: Cannot find implementation or library stub for module named 'omegaconf'
hydra/plugins/completion_plugin.py:7: error: Cannot find implementation or library stub for module named 'omegaconf'
hydra/_internal/core_plugins/basic_launcher.py:6: error: Cannot find implementation or library stub for module named 'omegaconf'
hydra/_internal/plugins.py:6: error: Cannot find implementation or library stub for module named 'omegaconf'
hydra/_internal/hydra.py:10: error: Cannot find implementation or library stub for module named 'omegaconf'
hydra/main.py:11: error: Function is missing a type annotation for one or more arguments
Found 14 errors in 12 files (checked 1 source file)
```
As for git:
```
$ git --version
git version 2.21.1
```

**Comment by asottile** [comment]
for that, read the README

**Comment by omry** [comment]
Adding the missing library as an explicit additional dependency gets me what I want.
```

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies: [omegaconf==2.0.0rc3]
```
