### ISSUE TITLE
pre-hook finds error: unused 'type: ignore' comment while local mypy doesn't

### ISSUE THREAD

**Issue by euri10** [pre-commit/mirrors-mypy#11]
hello, pre-commit finds some `error: unused 'type: ignore' comment`  while local mypy doesn't.

```
git:(master) ✗ mypy src/settings.py
Success: no issues found in 1 source file
```
```
git:(master) ✗ pre-commit run mypy --verbose --files src/settings.py
mypy.....................................................................Failed
- hook id: mypy
- duration: 0.32s
- exit code: 1

src/settings.py:15: error: unused 'type: ignore' comment
src/settings.py:31: error: unused 'type: ignore' comment
Found 2 errors in 1 file (checked 1 source file)
```

my pre-commit config is below, it uses same version as mypy local.
the discrepancy disappears if I uncomment the `#        args: [--no-warn-unused-ignores]` line but that's not what I got in my mypy.ini so that would seem a rather harsh fix:

```
git:(master) ✗ cat .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
#        args: [--no-warn-unused-ignores]                          
```

local mypy version with it's configL

```
 git:(master) ✗ pre-commit --version
pre-commit 1.21.0
git:(master) ✗ mypy --version
mypy 0.761
git:(master) ✗ cat mypy.ini 
[mypy]
python_version=3.8
platform=linux

follow_imports = silent
disallow_any_generics = True
ignore_missing_imports = True

# be strict
disallow_untyped_calls=True
warn_return_any=True
strict_optional=True
warn_no_return=True
warn_redundant_casts=True
warn_unused_ignores=True

# for strict mypy: (this is the tricky one :-))
disallow_untyped_defs = True
check_untyped_defs = True
```
