### ISSUE TITLE
pre-commit passing non-python files to mypy

### ISSUE THREAD

**Issue by lonkeknol** [pre-commit/mirrors-mypy#14]
If there are non-python files (e.g. .yml, .html) in your repo, pre-commit will pass all individual files to mypy, which makes it fail. I added this to let mypy figure out what to parse:
```
 hooks:
     -  id: mypy
        pass_filenames: false
        args:
        - .
```
Did I diagnose this correctly, and if so, is it a good idea to add this to the readme?
