### ISSUE TITLE
Module 'typing' has no attribute 'TypedDict'; maybe "_TypedDict"?

### ISSUE THREAD

**Issue by jaywhy13** [pre-commit/mirrors-mypy#17]
I have the following in my code that the `mypy` pre-commit hook complains about:

```
from typing import TypedDict

```

I have the following configuration in my `pre-commit-config.yaml`.
```
exclude: "^$"
fail_fast: false
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        language_version: python3.8
```

`TypedDict` is added in Python 3.8. I changed the `language_version` and tried doing a `pre-commit clean` then `pre-commit install` but it's still complaining about the same error. I'm not sure what's causing this but it would seem as if it's not running `mypy` under a Python 3.8 virtualenv. I'm using `pyenv-virtualenv` and `pyenv` but from the `pre-commit` docs it seems `mypy` should be run in an isolated virtualenv so I don't think this should affect anything. 🤷
