### ISSUE TITLE
error: Duplicate module

### ISSUE THREAD

**Issue by KotlinIsland** [pre-commit/mirrors-mypy#19]
windows 10 1803
pre-commit 2.4.0

repo:
```
root
├── .pre-commit-config.yaml
└── foo
    └── a.py
```
.pre-commit-config.yaml:
```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    - id: mypy
      args: ["--strict", "foo"]
```

```
> pre-commit run -a
mypy.....................................................................Failed
- hook id: mypy
- exit code: 2

foo\a.py: error: Duplicate module named 'a' (also at 'foo\a.py')
Found 1 error in 1 file (checked 2 source files)
```
