### ISSUE TITLE
Different behavior to mypy when using local stubs 

### ISSUE THREAD

**Issue by KotlinIsland** [pre-commit/mirrors-mypy#20]
```
foo
├── __init__.py
├── a.py
├── b.py
└── b.pyi
```
.pre-commit-config.yaml
```yaml
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    - id: mypy
      args: ["--strict"]
```
a.py:
```py
from .b import b
reveal_type(b)
```
b.py:
```py
```
b.pyi
```
b: int
```
```
> pre-commit run mypy -a
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

foo\a.py:1: error: Module 'foo.b' has no attribute 'b'
foo\a.py:3: note: Revealed type is 'Any'
Found 1 error in 1 file (checked 3 source files)

> mypy --strict foo
foo\a.py:3: note: Revealed type is 'builtins.int'
```
