### ISSUE TITLE
What's the best way to specify the PYTHONPATH?

### ISSUE THREAD

**Issue by AdrienLemaire** [pre-commit/mirrors-mypy#21]
I'm using the following pre-commit spec:
```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
        additional_dependencies: [django-stubs==1.5.0]
        args:
          [
            --config-file=v2/mypy.ini
          ]
```
and I have a django project in the directory `v2/` with the following mypy.ini conf
```ini
[mypy]
disallow_untyped_defs = True
ignore_missing_imports = True
follow_imports = skip
show_column_numbers = True
plugins =
    mypy_django_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = "v2.settings.dev"
```

Running mypy from the v2/ dir works fine.
But to get the pre-commit hook running without ModuleNotFoundError, I need to execute
```console
$ PYTHONPATH=/home/dori/.virtualenvs/myenv/lib/python3.8/site-packages:v2/ git commit -am "fix: mypy conf"
```
Which is really not ideal. I couldn't find a way to specify the PYTHONPATH with pre-commit. 

Do you know of an automated way to teach the pre-commit mypy how to find my python modules?
