### ISSUE TITLE
"files" configuration in mypy.ini is ignored

### ISSUE THREAD

**Issue by stinodego** [pre-commit/mirrors-mypy#24]
I am trying to run `mypy` on just my `src` folder (and thus excluding the `tests` folder, where I do not use type hints). I set the `files` configuration in my `mypy.ini` file, but this only works when running locally; the pre-commit hook does not pick it up.

Here's the file contents:
```
# mypy.ini

[mypy]
plugins = pydantic.mypy
ignore_missing_imports = True
disallow_untyped_defs = True
files = src
```
```
# .pre-commit-config.yaml

repos:
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.782
      hooks:
      - id: mypy
        additional_dependencies: [pydantic==1.6.1]
```

With this setup, I will get mypy errors from the pre-commit hook on my `tests` folder. In contrast, when adding the `files: src` argument in the pre-commit hook instead, it __does__ work as expected!
```
# .pre-commit-config.yaml

repos:
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.782
      hooks:
      - id: mypy
        files: src  # -> This works!
        additional_dependencies: [pydantic==1.6.1]
```

Relevant detail: I am sure that the `mypy.ini` file is actually being read, as removing the `plugins` line will cause an expected error.

Is this a bug, or is this expected behaviour?

_(Sorry for all the edits, I accidentally hit 'post')_
