### ISSUE TITLE
Question - Does it respect mypy.ini by default?

### ISSUE THREAD

**Issue by imkaka** [pre-commit/mirrors-mypy#28]
I have both `mypy.ini` and `.pre-commit-config.yaml` in project root.

```
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
  - id: mypy
    name: Mypy typing checks
    exclude: ^api/settings.py
```
This does not respect mypy.ini

but this works!!

```
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
  - id: mypy
    name: Mypy typing checks
    args: ["--config-file=mypy.ini"]
    exclude: ^api/settings.py
```

am I missing anything here?

**Comment by asottile** [comment]
"doesn't work" isn't a bug report, show your expected behaviour, what you're seeing, and your `mypy.ini`.

it should respect it by default (it just calls `mypy filename filename filename` after all!)

**Comment by imkaka** [comment]
Hey @asottile, thank you for the response, sorry for the incomplete question. Please find the details below.

```
mypy.ini
[mypy]
python_version = 3.6
# ignore_missing_imports = True
follow_imports = silent
no_site_packages = True
strict_equality = True
no_implicit_optional = True
warn_unused_ignores = True
warn_no_return = False
warn_unreachable = True
show_error_codes = True
show_error_context = True
show_column_numbers = True
pretty = True
```
I commented out `ignore_missing_imports` to check if `mypy.ini` is respected.

pre-commit config.
```
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
  - id: mypy
    name: Mypy typing checks
    exclude: ^api/settings.py
```
Output
```
Flake8...................................................................Passed
Pretty format JSON...................................(no files to check)Skipped
Mypy typing checks.......................................................Passed
black....................................................................Passed
```

Case 2 - same `mypy.ini`
pre-commit config changed to
```
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
  - id: mypy
    name: Mypy typing checks
    args: ["--config-file=mypy.ini"]
    exclude: ^api/settings.py
```

Output

```
Flake8...................................................................Passed
Pretty format JSON...................................(no files to check)Skipped
Mypy typing checks.......................................................Failed
hookid: mypy

api/flexi_pass/services.py:9:1: error: Cannot find implementation or library
stub for module named 'django.utils'  [import]
    from django.utils import timezone
    ^
api/flexi_pass/services.py:9:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
api/flexi_pass/services.py:11:1: error: Cannot find implementation or library
stub for module named 'django.conf'  [import]
    from django.conf import settings
    ^
Found 2 errors in 1 file (checked 1 source file)

black....................................................................Passed
```


It respected the missing-imports flag here which is off in mypy.ini

Am I missing something?
