### ISSUE TITLE
Using --pretty prints each word of error on new line

### ISSUE THREAD

**Issue by verhovsky** [pre-commit/mirrors-mypy#29]
I want mypy to show the line on which an error occurs, using [the `--pretty` argument](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-pretty), the problem is that when run outside of precommit, the output looks like this:

```
$ python3 -m mypy --pretty test.py 
test.py:4: error: "list" is not subscriptable, use "typing.List" instead
    def do_the_thing(my_arg: str) -> list[str]:
                                     ^
Found 1 error in 1 file (checked 1 source file)
```

but when running mypy through pre-commit with the following config:

```yaml
default_language_version:
    python: python3.8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.790'
    hooks:
    -   id: mypy
        args: ['--pretty']
```

I see this:

```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

test.py:4: error:
"list"
is
not
subscriptable,
use
"typing.List"
instead
    ...f do_the_thing(my_arg: str) -> list[str]:
                                      ^
Found 1 error in 1 file (checked 1 source file)
```
