### ISSUE TITLE
`pre-commit run mypy` has a different behavior than `mypy` regarding giving preference to `.pyi` files over `.py`

### ISSUE THREAD

**Issue by tadeu** [pre-commit/mirrors-mypy#33]
I've created a minimal working example here: https://github.com/tadeu/pre-commit-mypy-issue

It's about this exact situation described in [`mypy` documentation](https://mypy.readthedocs.io/en/stable/stubs.html#index-0):

> If a directory contains both a `.py` and a `.pyi` file for the same module, the `.pyi` file takes precedence. This way you can easily add annotations for a module even if you don’t want to modify the source code. This can be useful, for example, if you use 3rd party open source libraries in your program (and there are no stubs in typeshed yet).

The problem is that `mirrors-mypy` is passing all files explicitly in the command line, and it seems to be passing the `.py` files instead of the `.pyi` files in this case:

```
$ pre-commit run mypy -a
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

src/example/__init__.py:6: error: Function is missing a type annotation  [no-untyped-def]
src/example/something.py:5: error: Call to untyped function "Example" in typed context  [no-untyped-call]
Found 2 errors in 2 files (checked 2 source files)
```

**Comment by asottile** [comment]
this tool just calls mypy -- there's no code here

**Comment by tadeu** [comment]
Yeah, the problem is exactly in _the way_ `mypy` is called. In this case, just `mypy` works, but `mypy src/example/__init__.py src/example/something.py` doesn't, because then `mypy` is being instructed to explicitly check `__init__.py`, so its rule about "`.pyi` file taking precedence" can't kick in.

Could it be a `mypy` "problem"? I'll open an issue there too.

**Comment by asottile** [comment]
calling `mypy` as just `mypy` doesn't gel nicely in that it wastes a bunch of execution time linting the whole codebase and unrelated files to what's being committed.  if mypy doesn't notice `.pyi` when running `mypy filename.py` that sounds like a mypy problem

#20 is also a duplicate

**Comment by s-weigand** [comment]
After just adding stubs I had the same issue.
My wasteful but working workaround is to just run `mypy` on the whole source folder, as I would from the command line.
By using [`pass_filenames: false`](https://pre-commit.com/#hooks-pass_filenames) you prevent `pre-commit` from passing the staged files to `mypy`. Hope this helps someone 😄 

```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        exclude: ^docs
        args: ["--ignore-missing-imports", "--scripts-are-modules", <project_source_dir>]
        pass_filenames: false
```

My guess is that this issue boils down to a difference between how `mypy` processes folders (where it possibly swaps `*.py` files for `*.pyi` files) and file paths (possibly not filtering and/or looking up) as arguments.

@tadeu could you please link the issue at `mypy` so I can follow it?

**Comment by max-sixty** [comment]
Are we sure this isn't just caused by `types: python` failing to include `.pyi` files?

Using this config picks up the errors in https://github.com/pydata/xarray/issues/5755

```yaml
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
        files: '.*\.py[i]?'
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
```

**Comment by max-sixty** [comment]
Right, but we do want it to be checked by mypy — that's my assumption.

**Comment by asottile** [comment]
that is a potential configuration -- yours [does not do that however](https://pre-commit.com/#filtering-files-with-types)

**Comment by max-sixty** [comment]
It sounds like you're suggesting there's something wrong with that config because of how pre-commit combines the filters? I'm not finding the brevity that constructive. We have a repro of it working, so something is failing.

I tried isolating why it correctly errors with the `.pyi` errors with the above config but not with the standard config from this repo on https://github.com/pydata/xarray/issues/5755. I think I binary searched it down:

```yaml
  - repo: local
    hooks:
      - id: mypy-local
        name: mypy
        entry: mypy
        language: python
        types: [python]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        exclude: "properties|asv_bench"

        require_serial: true
        # require_serial: true
```

It correctly errors when `require_serial` is commented out, which is surprising — any thoughts?

**Comment by asottile** [comment]
when that's commented out, mypy will get called many times with subsets of the file list (which likely changes how mypy considers modules since it follows imports)

**Comment by max-sixty** [comment]
One result for future travellers — changing the files filter _almost_ gets it to work, but mypy complains about duplicate modules:

```yaml
  - repo: local
    hooks:
      - id: mypy-local
        name: mypy
        entry: mypy
        language: python
        # types: [python]
        files: '.*\.py[i]?'
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        require_serial: true
```

```

xarray/core/_typed_ops.py: error: Duplicate module named "xarray.core._typed_ops" (also at "xarray/core/_typed_ops.pyi")
xarray/core/_typed_ops.py: note: Are you missing an __init__.py? Alternatively, consider using --exclude to avoid checking one of them.
Found 1 error in 1 file (errors prevented further checking)
```

which is the same as what it returns when both files are called concurrently:

```sh
mypy xarray/core/_typed_ops.pyi xarray/core/_typed_ops.py
```

**Comment by sziem** [comment]
I ran into this issue today after adding a `mypy-protobuf` stub file to my code.

I ended up using @max-sixty 's suggestion for the file pattern plus an explicit exclude of the file duplicated by the stub file, so that only the stub file is used for type-checking by mypy.

```yaml
  - repo: local
    hooks:
      - id: mypy-local
        name: mypy
        entry: mypy
        language: python
        types: [python]
        files: '.*\.py[i]?'
        exclude: '/path/to/file_that_exists_as_both_py_and_pyi.py'
        # args: ["--ignore-missing-imports", "--scripts-are-modules"] (add if you use them)
        require_serial: true
```

This is feasible, if the number of stub files is small and not expected to change.  If the number is large, I guess we'd need some kind of pattern to express that the `pyi` file is always to be preferred over the `py` file.  An ugly workaround could be to give all files with stubs a common suffix, so that they can be excluded with a pattern like `.*_suffix.py`
