### ISSUE TITLE
Add Mypy Daemon Hook

### ISSUE THREAD

**Issue by nplutt** [pre-commit/mirrors-mypy#35]
Hello!

Is this project open to adding another hook to allow the [Mypy Daemon server](https://mypy.readthedocs.io/en/stable/mypy_daemon.html) to be run via a pre-commit hook? I believe adding something like this to the `.pre-commit-hooks.yaml` file would work.
```yaml
-   id: dmypy
    name: dmypy
    entry: dmypy run
    language: python
    types: [python]
    args: []
    require_serial: true
    additional_dependencies: []
```
Usage would then be very similar to the `mypy` hook but obviously with different accepted args.

**Comment by asottile** [comment]
probably easier to just use:

```yaml
    hooks:
    -   id: mypy
        entry: dmypy run
```

then there's no special hook necessary

I don't think dmypy fits well with the framework though, it requires a daemon to be set up and running separately but also in the same environment (which isn't really accessible)
