### ISSUE TITLE
`--exclude` flag in `pre-commit-config.yaml` NOT excluding for mypy in `args`

### ISSUE THREAD

**Issue by yehoshuadimarsky** [pre-commit/mirrors-mypy#42]
Relevant part of my `pre-commit-config.yaml`:

```yaml
minimum_pre_commit_version: 2.9.3
# exclude binary and csv files
exclude: \.(h5|csv)$
repos:
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.812
      hooks:
          - id: mypy
            args: [--exclude=".*(mkt_index_feats|technical_features)\.py", --ignore-missing-imports]
```

But `mypy` is NOT ignoring the file named `mkt_index_feats.py`. I've played with the regex endlessly, and even confirmed it works correctly when I invoke `mypy` directly on the command line (after commenting out that redundant part out of `setup.cfg`)

I'm on Windows in a Conda env FWIW. Thanks!
