### ISSUE TITLE
Is it possible to install additional dependencies from git?

### ISSUE THREAD

**Issue by danieleades** [pre-commit/mirrors-mypy#47]
i'm trying to install type-steps from the master branch of a git dependency that's ahead of the published version

**Comment by danieleades** [comment]
never mind. figured it out

```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        additional_dependencies:
          - git+https://github.com/tk0miya/docutils-stubs.git@master
 ```
