### ISSUE TITLE
Avoiding "Duplicate module"

### ISSUE THREAD

**Issue by webknjaz** [pre-commit/mirrors-mypy#5]
If you have two modules with the same name in the project (but in different packages!) this hook will fail with `--all-files` supposingly because `pre-commit` will pass a list of individual files there.

Not sure what the proper solution should be but it seems like a good idea to have something like `--all-files=./folder` on the hook runner side allowing the user to pass a folder there or maybe an extra option in the hook definition for that dir.

https://github.com/python/mypy/issues/4008#issuecomment-434869336

```console
pre-commit run-test: commands[0] | python3 -m pre_commit run mypy --all-files -v
[mypy] mypy..............................................................Failed
hookid: mypy

octomachinery/app/action/config.py: error: Duplicate module named 'config' (also at 'octomachinery/app/server/config.py')
```

@asottile what do you think?

**Comment by asottile** [comment]
this is usually due to mypy not really understanding PEP420 namespaces -- usually the fix is to add `__init__.pyi` or `__init__.py` files

**Comment by asottile** [comment]
but, if you want what you're suggesting, there's already a way to do that:

```yaml
-   repo: ...
    rev: ...
    hooks:
    -   id: mypy
        name: mypy (server)
        files: ^server/
    -   id: mypy
        name: mypy (client)
        files: ^client/
```

for example

**Comment by webknjaz** [comment]
@asottile in my case its namespaces. So I really only want to pass a top-level dir. Running mypy manually works:
```console
$ ~/.cache/pre-commit/repooniuegcn/py_env-python3/bin/mypy .

$ echo $?                                                   
0
```

What you're suggesting in your second comment is not what I'm asking. I don't want to filter out files, I want to pass a directory name and I want pre-commit to bypass that as is w/o trying to traverse that into individual file paths before calling `mypy`.

**Comment by asottile** [comment]
Here's how you can do what you want, though note that it's not usually desirable since it will lint more than the files you're changing on commit which will usually be much slower:

```yaml
-   repo: ...
    rev: ...
    hooks:
    -   id: mypy
        files: ^server/
        entry: mypy server/
        pass_filenames: false
```
