### ISSUE TITLE
Error while loading mypy configuration

### ISSUE THREAD

**Issue by mlhamel** [pre-commit/mirrors-mypy#58]
When defining the mypy configuration like that:
```yaml
-   repo: git@github.com:pre-commit/mirrors-mypy.git
    rev: v0.910
    hooks:
    - id: mypy
      args: [--config-file mypy.ini]
```
I've got the following error:
```bash
mypy.....................................................................Failed
- hook id: mypy
- exit code: 2

mypy: can't read file '--config-file mypy.ini': No such file or directory
```

Is there a way to point to the right path?
