### ISSUE TITLE
pre-commit should deal with the --python-version parameter

### ISSUE THREAD

**Issue by crusaderky** [pre-commit/mirrors-mypy#66]
[dask/distributed](https://github.com/dask/distributed/) is a Python 3.8+ project that uses Python 3.9-style delayed annotations:

```python
from __future__ import annotations

x: dict[str, int]
```
This works:
```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
```
This breaks, complaining that dict is not subscriptable:
```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
```
This is because mypy 0.940 changed from defaulting from the latest supported version of python to the currently running one.

Fix:
```yaml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
          - --python-version 3.10
          - "3.10"
```
The issue is awkward, as mypy pre-commit makes no mention of which python version it runs on (by reading the code, it's whatever is installed by ``actions/setup-python@v1``).
This was fine before mypy 0.940, but now IMHO the ``--python-version`` parameter should either be made into an explicit pre-commit parameter (like for e.g. black or pyupgrade pre-commit) or default to the latest version of python.
