### ISSUE TITLE
'rev' does not seem to work

### ISSUE THREAD

**Issue by RayBB** [pre-commit/mirrors-mypy#69]
The docs give this example:
```
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
```

However, when I specify `rev: 'v0.942'` it seems like I'm still getting `rev: 'v0.950'` which has some breaking changes for my project.

I poked around at the code and it's not clear to me how the `rev` param is used.

Any suggestions for pinning to a specific version?

**Comment by asottile** [comment]
can you share an example? you can also put `args: [--version]` and run with `--verbose`

show your full configuration and the command you're running, I can't see your screen

**Comment by RayBB** [comment]
It took me a while to figure out that if I add `--version` it will always pass and that's why you said to add `--verbose` separately.

I spent a while trying to get a reproducible example but I haven't gotten to the point of any explanation.

It seems to be more related to github actions than your plugin though.

Here's the config for mypy I'm using
```
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
      - id: mypy
        args: [--verbose]
        exclude: db/migrations/|alembic/versions/ # this should always match what's excluded in mypy.ini
        additional_dependencies:
          - 'types-all'
          - 'pydantic' # https://github.com/dropbox/sqlalchemy-stubs/issues/63#issuecomment-876347216
          - 'sqlalchemy-stubs'
```

I don't think it'll help much but this is the mypy error:
```
external/mailgun.py:280: error: Argument "files" to "post" has incompatible type "Optional[List[Tuple[str, Tuple[str, str, str, Dict[Any, Any]]]]]"; expected "Optional[Union[Mapping[str, Union[SupportsRead[Union[str, bytes]], str, bytes]], Mapping[str, Tuple[Optional[str], Union[SupportsRead[Union[str, bytes]], str, bytes]]], Mapping[str, Tuple[Optional[str], Union[SupportsRead[Union[str, bytes]], str, bytes], str]], Mapping[str, Tuple[Optional[str], Union[SupportsRead[Union[str, bytes]], str, bytes], str, MutableMapping[str, str]]]]]"
Found 1 error in 1 file (checked 200 source files)
```

## While running in GitHub Actions
* I see `LOG:  Mypy Version:           0.942` - so I can confirm that the rev is working as expected
* However, we still have mysterious mypy error above still occurring despite no recent changes to any dependency or file. GitHub actions for mypy pre-commit that were successful earlier this week, if rerun, start to fail.

## While running locally
* I run `pre-commit run --all-files`
* If my pre-commit config has `v0.942` there is absolutely no error
* As soon as I upgrade to `v0.950` I start to see the same error as in GitHub actions

That being said, I'm not sure what to make of all of this. Perhaps it's an issue with the [pre-commit github action](https://github.com/pre-commit/action) that's in maintenance mode. Or perhaps there is some weird cache issue with github actions in general. If you think it's worth it, I could try to create a public repo reproducing this in a minimal way. 

Or if you think the logs when using `--verbose` would help I can upload them but I need to comb through and make sure they don't have anything sensitive in them. 

If this seems like it's not related to this repo feel free to close this.

Thanks again for all your work maintaining this great project!
