### ISSUE TITLE
Poetry dependencies integration

### ISSUE THREAD

**Issue by mattyclarkson** [pre-commit/mirrors-mypy#77]
It would be good to know the best practice for installing types for `mypy` that are managed in a modern Python dependency tool such as [Poetry](https://python-poetry.org/) or [Flit](https://flit.pypa.io/).

When running `mypy` hook on a Poetry project, the dependencies required for `mypy` to correctly do static analysis are held and managed in `pyproject.toml`.

These may be held in a `dev` or `types` Poetry [dependency group](https://python-poetry.org/docs/managing-dependencies/#dependency-groups).

One _could_ replicate the dependencies within `additional_dependencies` but that duplicates the management of the dependencies.

Another way is to do the following:

```
- id: poetry-export
  args: ["--only", "types", "-o", "requirements-mypy.txt"]
- id: mypy
  additional_dependencies:
    - requirements-mypy.txt
```

The optimal would be to be able to install the dependencies through `additional_dependencies` naturally.

One _could_ put the [dependencies into an extra](https://peps.python.org/pep-0621/#recommend-that-tools-put-development-related-dependencies-into-a-dev-extra):

```
- id: mypy
  additional_dependencies:
    - .[types]  # not really sure if this is the correct syntax
```

If this is the preferred way, it might be possible to allow an extension to Poetry that allows an mapping between dependency groups and adding them as extras to the built package.

---

Another more invasive option would be a new installation command support in `pre-commit`:

```
- id: mypy
  additional_dependencies:
    - poetry==1.2.0
  install_dependencies: poetry install --only types
```

That's pretty horrible though.
