### ISSUE TITLE
Not respecting excluded files in pyproject.toml

### ISSUE THREAD

**Issue by impresionista** [pre-commit/mirrors-mypy#89]
Hi! I've ignored some files in `pyproject.toml` using `exclude = ['path1/file1.py', 'path2/file2.py']`. If I run mypy mannualy, those files are ignored correctly but if I modify one of the files, pre-commit mypy does not respect the `exclude` and run on that file. I'm not sure if I'm doing something wrong.

Here are my settings/environment:

- Using Python 3.10.5
- Using `pyenv` form python version
- Using `virtualenv` for virtual environment

`pyproject.toml`:
```toml
...

[tool.mypy]
python_version = '3.10'
exclude = [
  'src/finance/main.py',
  'src/finance/clients/yahoo_finance.py',
]
follow_imports = 'skip'
strict = true
warn_return_any = false
ignore_missing_imports = true
scripts_are_modules = true
install_types = true
non_interactive = true
```

`.pre-commit-config.yaml`:
```yaml
repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.285
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'
    hooks:
      - id: mypy
```

Thanks!
